bridges:
  - ros_topic_name: /camera/image_raw
    gz_topic_name: /camera/image_raw
    # ros_type_name: sensor_msgs/Image
    # gz_type_name: ignition.msgs.Image
    direction: GZ_TO_ROS
    subscriber_queue: 10
    publisher_queue: 10
    lazy: true

  # - ros_topic_name: /camera/camera_info
  #   gz_topic_name: /camera/camera_info
  #   ros_type_name: sensor_msgs/CameraInfo
  #   gz_type_name: ignition.msgs.CameraInfo
  #   direction: GZ_TO_ROS
  #   subscriber_queue: 10
  #   publisher_queue: 10
  #   lazy: true
